### ISSUE TITLE
DivideError: integer division error

### ISSUE THREAD

**Issue by JasonFu1998** [NonlinearOscillations/HarmonicBalance.jl#27]
Is the integer division error shown in picture below caused by the parameter settings or code flaw?
<img src=https://user-images.githubusercontent.com/80552912/168022515-23e84c6a-e74d-4a4a-8034-285c2f9a059b.jpg width=75%>

**Comment by jkosata** [comment]
This problem is caused by version of Symbolics at and above 4.4.3. Older versions of HarmonicBalance will use the newest Symbolics and throw this error.

This issue does not appear in the current `master` branch of HarmonicBalance.

The General registry version of HarmonicBalance is being updated, should be done soon (https://github.com/JuliaRegistries/General/pull/60096), then you can `Pkg.update(HarmonicBalance)` to fix this.

**Comment by JasonFu1998** [comment]
Done! Thanks a lot!
