### ISSUE TITLE
Making plot recipes instead of multiple dispatch functions

### ISSUE THREAD

**Issue by oameye** [NonlinearOscillations/HarmonicBalance.jl#67]
It is recommended by the Plots.jl package to make plot recipes instead of multiple dispatch functions. Maybe we should explore this route. This would also easily resolve issue #59.

https://github.com/JuliaPlots/Plots.jl/tree/master/RecipesBase
https://docs.juliaplots.org/latest/recipes/

**Comment by jkosata** [comment]
Nice, this looks like some cool functionality. Wanna take a stab at implementing this? I might try otherwise.

**Comment by oameye** [comment]
@jkosata: You can do this for the already existing function, if you have the time... . I will resolve issue #63 and #37  in the recipeBase formula

**Comment by oameye** [comment]
> Nice, this looks like some cool functionality. Wanna take a stab at implementing this? I might try otherwise.

@jkosata When you have the time you're free to try it 😄!

**Comment by jkosata** [comment]
So I've taken a look and it seems like what we're doing now is more pain than it's worth to translate into recipes. This is because we don't have a straightforward map between an object and its plottable representation.

Our `plot` currently has a decision tree which looks for specific kwargs based on solution dimensionality (like `z` for 2D), while any other kwargs are passed to plotting. It's also overloaded to have `x` and `y` as either varargs or kwargs to save the pain in 1D plotting. In a `@recipe`, all kwargs are automatically fed into plotting and this is not possible.
