### ISSUE TITLE
Being able to export the precompilation results to a file

### ISSUE THREAD

**Issue by pepassaco** [NonlinearOscillations/HarmonicBalance.jl#69]
Hello!

I just wanted to write here an idea that would be extremely useful for accelerating simulation times. Once we have already compiled our system of differential equations, and once we can start changing parameters freely without having to wait again that long time, it would be pretty neat having the possibility to save to an offline file this result. this way, if on a different occasion we want to continue researching that new system after we had already closed Julia, we would not have to wait again for the compilation of the exact system. Specially for big systems, this could save a lot of time each day :)

Thanks and congratulations for this great package.

Pablo EA1FID

**Comment by oameye** [comment]
Hey Pablo, 

Thank you for the issue. Actually, it is unnecessary to implement this feature in this package. If you use [`JLD2.jl`](https://github.com/JuliaIO/JLD2.jl), you can export any variable of any type. And load it again in a different instance.

As an example:
```julia
using HarmonicBalance, FileIO, JLD2
@variables t x(t) y(t);
@variables ω₀ ω γ λ α η;

natural_equation = [d(d(x, t),t) + ω₀^2*(1-λ*cos(2*ω*t)) * x + γ*d(x,t)  + α*x^3 + η*d(x, t)*x^2]
dEOM = DifferentialEquation(natural_equation, [x, y])
add_harmonic!(dEOM, x, ω) # x will rotate at ω
harmonic_eq = get_harmonic_equations(dEOM);

jldsave("harmonic_eq.jld2"; harmonic_eq)
harmonic_eq = load("harmonic_eq.jld2", "harmonic_eq")

```

**Comment by pepassaco** [comment]
Ei! Thanks for the fast reply. Is that procedure still valid for saving the intermediate results after performing the initial warm_up? So that we can the play around with the fixed and varied variables to get different outcomes just by first importing the file

**Comment by oameye** [comment]
So after you load the slow- flow equations `harmonic-eq` you can use the previously computed equation to calculate the steady states for different parameters. However, you will always have to load the HarmonicBalance package by writing `using HarmonicBalance` and the first time the computation will be slower. This is because of the "Just-ahead-of-time" nature of [Julia](https://en.wikipedia.org/wiki/Julia_(programming_language)).

If I misunderstood your question, please say so!
