### ISSUE TITLE
Sorting in 2d parameter space

### ISSUE THREAD

**Issue by oameye** [NonlinearOscillations/HarmonicBalance.jl#84]
Credit to @jdelpino:
The labeling of the branches differ for one dimensional cut through 2two dimensional results and just one dimensional sweep. Is there a way to label them the same?
> The discrepancy is caused by your ambiguity when you sort in 2D parameter space. You can go along x, along y... and now we did it so it sorts according to the nearest neighbour. In 2D, you might be closer to a solution along the diagonal. (in parameter space) than to a solution that is in front of you along x. I think we could make the user decide if they want to sort along x or along y, instead of nearest neighbors.

Also the number of stable/unstable solutions differ?
> This seems to be caused by the reordering, therefore the branch assignment,  not doing a good job, since the number of solutions (curves) is probably the same in both cases.

![image](https://i.imgur.com/MNtFE2n.png)

**Comment by jkosata** [comment]
I'm not sure what the proposed functionality is here. The labeling is by definition arbitrary (unless one wants to do a _lot_ of detective work regarding homotopy tracking).

The ordering is set by `find_branch_order`, which currently makes real/stable solutions appear "first". In 1D, this means from the left, in 2D, this means from the corner of the array. You cannot really compare the orderings across different plots - there is no higher principle to fix them. 

The number of solutions is likely because as you expand parameter space, you simply find more real branches.
